spring.profiles.active=dev
spring.application.name=platzi-play

# 1. Usa 'server' en lugar de 'spring' para el contexto (Es el estándar de la v4)
# server.servlet.context-path=/platzi-play/api

# 2. Configuración limpia para Swagger en Spring Boot 4
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# Quitamos el 'use-root-path' porque se está "pisando" con el context-path